### ISSUE TITLE
Project Philosophy and Design

### ISSUE THREAD

**Issue by ViViDboarder** [ForceCLI/force#218] opened 2015-11-18 19:48 UTC
I use `force` daily as my primary tool for my individual development along with a few plugins I've developed using this tool.

The current project is difficult to follow due to inconsistent merges and no clear indication of the project goals. This results in unexpected changes breaking interfaces and forcing extra work in order to make sure everything continues to work.

If this is really going to be a useful, long-term open source project (which I would love to keep contributing to), it would be benefit by having some kind of a roadmap and even a proposal of new features as a heads-up to those following and depending on the project.

**Comment by delbydev** [comment] 2015-11-19 10:55
The conscious efforts of everyone involved have made this in my opinion a beautiful product.  Just that using it and keeping up with changes are rapidly becoming two separate activities that are not easily tackled together.  Some user activities such as mine are dependent on a stable release being maintained, and then absorbing a change or set of changes when a new release has stabilised after new function testing, regression testing and acceptance testing.  These activities are costly on time so we shan't pretend this utopia will ever exist unless it becomes a commercial venture, which would bring its own challenges such as motivation etc.   But there perhaps might be steps to protect the quality of the product in the meantime?

As another user of force, and happy to recommend it to any developer or data analyst, I would second all  sentiments from ViViDboarder.  But added to that, the project has reached a maturity where it deserves multiple releases, simply because the product is rich in features and is very practical for rapid data shifting to and from salesforce.com

With a nudge in the right direction from the developers - I would, if agreeable with the team, be happy to assist where I can with the growth of the product.  I should be able to help with testing, but caveat only with specific feature changes rather than full regression testing when new features are enlisted.  In fairness my usage of this product is very limited because my view of SalesForce is just that. 

Perhaps to ring-fence the general user community, the usual software development phases could maybe applied?
Could a STABLE build be left - for those that need to use the utility daily for regular data processing and analysis activities.
Development - (bleeding edge)
Test / Beta.
etc ...

I will be happy to get involved, but it might need some time with the architects to ascertain the aspirations, roadmap and practicalities of a multi-phase release process.

**Comment by dcarroll** [comment] 2015-11-23 18:30
First, thank you for your commitment to this project.  I would love all the help that I can get on this.  Although I am an employee of Salesforce, this CLI is still a labor of love for me and I do what I can when I can. So I really appreciate the effort by all contributors.

This is not the first developer tool I have written here and one of the goals of this project, as with the others, is for it to eventually be taken over by Salesforce internal R&D as an open source project, enjoying the resources of a development team including QA and release goals.  This may not happen.  

I agree there is significant technical debt around testing.  And the debt only grows as the tool matures.  I am open to any suggestions to mitigate this issue as mentioned by using stable or dev branches as necessary.  

It is my opinion that the core of the CLI should be stable and slowly changing and instead of the monolithic app that is today, consist of the core + modules in the manner of plugins. Just don't know how to do that in this environment.

A little history.  This CLI was originally developed by David Dollar at Heroku.  Mr. Dollar was using this as a test bed for go as a possible language for the re-write of the Heroku CLI.  Mr. Dollar and I worked together on the initial CLI with me acting as the domain expert for Force.com APIs. David has since left Heroku and I have continued to maintain this project as it is a better, more flexible alternative to the Java/Ant solution that preceded it.  Prior to inheriting this, I did not know go and would still consider myself a novice.  Caveat Emptor.

Please suggest how you would like to see this project move forward.

Thanks again for your support.

**Comment by cwarden** [comment] 2015-11-23 20:53
Given the current state of the code, maintaining a stable branch doesn't seem feasible.  It's going to be hard to know what changes, other than perhaps minor bug fixes, to pull into the stable branch.  So the stable branch would likely stay stuck at whatever version the branch is spawned from.  Someone looking for stability might as well just stick with whichever tagged revision they've tested.  @dcarroll has done a good job tagging new releases.

I think getting to a point where non-breaking changes could be pulled into a stable branch, or semantic versioning could be used, requires that the code starts getting covered by tests.

Writing tests for all of the existing code probably won't happen (unless Salesforce or someone wants to sponsor such work), but the project could adopt a requirement for test coverage on future changes that get merged.  This tends to be a little painful at the beginning as hard-to-test code needs refactoring, but I've found it to be successful on projects that have been under development for a long time without tests.

Like @dcarroll, I also consider myself a golang novice.  Perhaps a more seasoned go developer can suggest a test library to adopt.  I prefer BDD-style libraries in which the tests also serve as specs (not necessarily cucumber-style ones that require tests be written in a custom DSL), but I'm happy to try my hand at whatever the project adopts.

**Comment by sebastianclaros** [comment] 2015-12-01 14:14
I'm a new contributor, honestly I'm learning go with this project. 

I tried to add functionality reading other parts of the code, but I found that there are different ways or styles. I think that is good to have some sort of best practices or like patterns and anti-patterns, because there some parts that are very similar in all the commands (like defining and parsing of the command line). 

My next step is to create the unit test of my part, and I think that if @dcaroll ask us to create unit test before doing the pull request, will be quick win, because we focus in the more unstable part as a first step.

What do you think of [Ginko](https://onsi.github.io/ginkgo) (a BDD framework for Go)  

Thanks for giving us the chance of being part of this project.

**Comment by cwarden** [comment] 2015-12-01 21:38
Ginkgo looks good to me.  I tried it out in my most recent pull request, #221.

**Comment by cwarden** [comment] 2015-12-01 23:57
Ginkgo only supports Go 1.3+.  Travis CI is configured to build for 1.1 and 1.2 as well.  Is 1.1 and 1.2 support important?

**Comment by dcarroll** [comment] 2015-12-02 00:37
If we go this way, it would seem a good reason to abandon 1.1 and 1.2
support. Will result in faster Travis results as well.

On Wed, Dec 2, 2015 at 8:57 AM, Christian G. Warden <
notifications@github.com> wrote:

> Ginkgo only supports Go 1.3+. Travis CI is configured to build for 1.1 and
> 1.2 as well. Is 1.1 and 1.2 support important?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/218#issuecomment-161135969>.
>



-- 
Thanks,
Dave

**Comment by ViViDboarder** [comment] 2015-12-02 02:07
Thanks everyone for taking interest! And thanks a ton @dcarroll for taking this project on from the SFDC side.

One thing I've seen a lot of successful, large, open source projects do is to leverage issues as a notification/discussion forum (like we are doing now) and to follow the same code review model for all changes. From core contributors or non-core. 

You can see a similar process if you look at something like Neovim. Major changes are discussed prior to development by means of creating an issue with some sort of label indicating it's an RFC. This notifies any users that follow this project of any new proposed ideas as well as allows people to speak up if they have a better idea or if the proposal breaks some key use cases before development time is spent.

The other key thing is that all changes go through a Pull Request. This ensures that everyone is able to track any and all changes that they might be interested in rather than having to passively monitor the master branch. It also makes it easier to adhere to a consistent design.

Does this sound like it would be useful to anyone? @dcarroll as the primary core contributor here, what do you think about this?

**Comment by dcarroll** [comment] 2015-12-02 02:25
I think this is great.  I agree with the pull requests as I learned the
hard way that committing to master branch screws things up.  It's why I
develop in a forked repo on my own git account and create pull requests.

A related workflow is that the distribution binaries are not updated until
triggered by a new release.  This may not be the right way if all
development and testing is done to an "unstable" branch and once the
"unstable" branch is blessed, a pull request to merge unstable with master
could trigger the cross platform compilation and publication to the binary
store (S3).  Right now, I need to create a new release that triggers the
process.

The other issue that I am concerned about is bloat of the CLI.  I've been
thinking about a redesign, maybe a v1.0 that has a core CLI and plugins
that can be installed by the user to add important, yet less demanded
features.  The goal is to keep the core as stable as possible and accept
new features without impacting the core.

As mentioned earlier, providing a consistent argument handler is also on
the back log. Parsing the arguments based on number and position is not
workable but was the original method.

On Wed, Dec 2, 2015 at 11:07 AM, Ian <notifications@github.com> wrote:

> Thanks everyone for taking interest! And thanks a ton @dcarroll
> <https://github.com/dcarroll> for taking this project on from the SFDC
> side.
>
> One thing I've seen a lot of successful, large, open source projects do is
> to leverage issues as a notification/discussion forum (like we are doing
> now) and to follow the same code review model for all changes. From core
> contributors or non-core.
>
> You can see a similar process if you look at something like Neovim. Major
> changes are discussed prior to development by means of creating an issue
> with some sort of label indicating it's an RFC. This notifies any users
> that follow this project of any new proposed ideas as well as allows people
> to speak up if they have a better idea or if the proposal breaks some key
> use cases before development time is spent.
>
> The other key thing is that all changes go through a Pull Request. This
> ensures that everyone is able to track any and all changes that they might
> be interested in rather than having to passively monitor the master branch.
> It also makes it easier to adhere to a consistent design.
>
> Does this sound like it would be useful to anyone? @dcarroll
> <https://github.com/dcarroll> as the primary core contributor here, what
> do you think about this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/218#issuecomment-161156395>.
>



-- 
Thanks,
Dave

**Comment by ViViDboarder** [comment] 2015-12-02 02:32
Yea, I think feature based and atomic pull requests to master and then tagging releases to trigger a binary build works pretty well for many projects, though I'm admittedly no expert in the matter. Perhaps it can be automated by tagging the master branch so you're not having to really do anything manual other than create the tag.

As for the future design regarding a plugin based system, I think that's a great first use of an RFC ticket! Assuming we all agree on that as a procedure, of course.

Following a model similar to `git` could be nice in that it is familiar to many developers already. Git is also extensible by creating additional plugins. We could elaborate on the new ticket though.

**Comment by ViViDboarder** [comment] 2015-12-02 02:33
Another side note... is there a ticket for refactoring a consistent arg parser? It might be worth starting a discussion on that as well so we can collectively research and or begin experimenting.

**Comment by dcarroll** [comment] 2015-12-02 03:05
Ian, would you mind creating the "ticket" so that I fully understand how it
is identified as such?

On Wed, Dec 2, 2015 at 11:33 AM, Ian <notifications@github.com> wrote:

> Another side note... is there a ticket for refactoring a consistent arg
> parser? It might be worth starting a discussion on that as well so we can
> collectively research and or begin experimenting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heroku/force/issues/218#issuecomment-161160098>.
>



-- 
Thanks,
Dave

**Comment by orospakr** [comment] 2016-04-26 17:56
Btw did anyone look at goconvey as a ginkgo alternative? Don't know which is "better", just curious if it was on the radar.

**Comment by cwarden** [comment] 2022-11-09 15:25
Still working toward 1.0.  Argument parsing was rewritten in 7242507a005775ab0af835864e67394f11c4ce40.

**Comment by cwarden** [comment] 2023-04-19 12:45
Closing.  Version 1.0 released.

**Closed by cwarden** 2023-04-19 12:45 UTC
