### ISSUE TITLE
soap login doesn't escape invalid xml characters in username and pasword

### ISSUE THREAD

**Issue by abeyer** [ForceCLI/force#354] opened 2016-12-11 01:04 UTC
Getting an error trying a SOAP login on linux:

$ force login -u=... -p=...
ERROR: parse :///id//: missing protocol scheme

**Comment by TheLonelyGhost** [comment] 2016-12-13 18:53
Also the case on Windows. It looks like something on the SOAP API's end is screwy.

**Comment by cwarden** [comment] 2016-12-13 19:17
If you can build the application from source, try running 4666f97a496cdb547784f6a9299f09ebf52fd933.  You should sanitize the `<sessionId>` in the output before sharing it.

**Comment by cwarden** [comment] 2016-12-13 19:25
Here are binaries of 4666f97a496cdb547784f6a9299f09ebf52fd933: https://gist.github.com/cwarden/87e280873447c8eb4e79a144851aac11

**Comment by abeyer** [comment] 2016-12-13 22:46
soap.go is building xml soap payloads just using `fmt.Sprintf` without properly escaping characters which aren't valid xml.

abeyer/force@d24b041 xml encodes the login request, and fixes the problem that I'm hitting. However, that's only the login request -- I strongly suspect the `Execute` function also has escaping bugs lurking somewhere, as it's building the request the same way.

**Comment by cwarden** [comment] 2016-12-13 22:53
Thanks, @abeyer.  I'm able to reproduce now with `force login -i login -u user@example.com -p 'test<'`.

**Comment by allensu1994** [comment] 2017-03-30 14:13
I just got the same error without any special characters in my username or password (only alphanumeric).

Loaded Endpoint: (https://xxxxxxxxxxx-dev-ed.lightning.force.com)
ERROR: parse :///id//: missing protocol scheme

**Comment by dcarroll** [comment] 2017-03-30 19:13
This is a different error. So, it turns out that if you are using soap with mydomains, the login url pattern is

`https://login.salesforce.com/services/Soap/c/39.0/<org_id>`

Or, you need to use the my domain url for classic

`https://xxxxxxxxxxx-dc-dev-ed.my.salesforce.com`

This was not clear.  Please try using the my.salesforce.com url and see if that works for you.

**Comment by dcarroll** [comment] 2017-03-30 19:33
I've added a check for the 405 error that is returned when it is not a valid url. The Parse error was misleading as that was being encountered during the attempt to parse out a Soap Error message that does not exist in the body returned when a 405 is encountered.

**Comment by abeyer** [comment] 2017-03-30 19:41
Shouldn't this remain open? The fix is only for the unrelated issue, I still don't see any fix for the XML problem this was originally about

**Comment by abeyer** [comment] 2017-03-30 19:47
I went ahead and put in a PR (#395) w/ my previous fix to that...not sure if that's an ideal solution, as I've never written any Go before, but seems to work and I haven't see any alternatives suggested or committed.

**Comment by dcarroll** [comment] 2017-03-30 19:51
Yes, you are right. I see the PR and will merge!

**Comment by dcarroll** [comment] 2017-03-30 20:01
Also, looks like the Travis build is failing. Are you using the latest .travis.yml?

**Comment by abeyer** [comment] 2017-03-30 21:33
ugh, looks like a `go get` failed, but I'm not sure how that's handled in travis...I'll have to dig into that after work.

**Comment by cwarden** [comment] 2018-01-31 19:29
This was fixed in #395, included in v0.23.0.

**Closed by cwarden** 2018-01-31 19:29 UTC
